language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/ZipArchiveExample.xcworkspace
matrix:
  include:
    - osx_image: xcode12
      env: OSX_IMAGE="xcode12"
           SDK="appletvsimulator"
           DEVICE="Apple TV 4K (at 1080p) (13.3)" # newest on travis for tvOS 14.x          

    - osx_image: xcode12
      env: OSX_IMAGE="xcode12"
           SDK="iphonesimulator"
           DEVICE="iPhone SE (2nd generation)" # newest on travis for iOS 14.x

before_install:
  - if [ ${SDK} = "macosx" ]; then
        SCHEME="ObjectiveCExample_macOS";
    elif [ ${SDK} = "appletvsimulator" ]; then
        SCHEME="ObjectiveCExample_tvOS";
    else
        SCHEME="ObjectiveCExample_iOS";
    fi
  - if [ ${SDK} = "macosx" ]; then
        DESTINATION="platform=macosx";
    else
        DESTINATION_UDID=$(instruments -s devices | grep "$DEVICE \[" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g');
        DESTINATION="id=$DESTINATION_UDID";
    fi

script:
  # Testing
  - xcodebuild
    `` -workspace Example/ZipArchiveExample.xcworkspace
    `` -scheme $SCHEME
    `` -sdk $SDK
    `` -destination "$DESTINATION"
    `` -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES
    `` $USEMODERNBUILDSYSTEM
    `` test
