language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/ZipArchiveExample.xcworkspace
matrix:
  include:
    - osx_image: xcode11.6
      env: OSX_IMAGE="xcode11.6"
           SDK="appletvsimulator"
           DEVICE="Apple TV 4K (at 1080p) (13.4)" # newest on travis for tvOS 13.x  

    - osx_image: xcode11.6
      env: OSX_IMAGE="xcode11.6"
           SDK="iphonesimulator"
           DEVICE="iPhone 11 Pro Max (13.6)" # newest on travis for iOS 13.x

before_install:
  - if [ ${SDK} = "macosx" ]; then
        SCHEME="ObjectiveCExample_macOS";
    elif [ ${SDK} = "appletvsimulator" ]; then
        SCHEME="ObjectiveCExample_tvOS";
    else
        SCHEME="ObjectiveCExample_iOS";
    fi
  - if [ ${SDK} = "macosx" ]; then
        DESTINATION="platform=macosx";
    else
        DESTINATION_UDID=$(instruments -s devices | grep "$DEVICE \[" | sed -E 's/.*\[([0-9A-F-]+)\].*/\1/g');
        DESTINATION="id=$DESTINATION_UDID";
    fi

script:
  # Testing
  - xcodebuild
    `` -workspace Example/ZipArchiveExample.xcworkspace
    `` -scheme $SCHEME
    `` -sdk $SDK
    `` -destination "$DESTINATION"
    `` -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES
    `` $USEMODERNBUILDSYSTEM
    `` test
